function y=rayleighMultipath(x,fs)

rayChan = comm.RayleighChannel(...
    'SampleRate',fs, ...
    'PathDelays',[0 1.5]/fs, ...
    'AveragePathGains',[2 3], ...
    'NormalizePathGains',true, ...
    'MaximumDopplerShift',30, ...
    'DopplerSpectrum',{doppler('Gaussian',0.6),doppler('Flat')}, ...
    'RandomStream','mt19937ar with seed', ...
    'Seed',22, ...
    'PathGainsOutputPort',true);
y=rayChan(x);
end