function y=riceanMultipath(x,fs)

ricianChan = comm.RicianChannel(...
               'SampleRate',fs,...
               'PathDelays',[0.0 1.8 3.4]/fs,...
                'AveragePathGains',[0 -2 -10],...
                'KFactor',4,...
                'DirectPathDopplerShift',5.0,...
                'DirectPathInitialPhase',0.5,...
                'MaximumDopplerShift',4,...
                 'DopplerSpectrum',doppler('Bell', 8),...
                 'RandomStream','mt19937ar with seed', ...
                 'Seed',73, ...
                 'PathGainsOutputPort',true);
    y=ricianChan(x);

end
