function res = applyChannel(x, channel, fs)

switch channel
    case {"Rayleigh"}
        rayChan = comm.RayleighChannel(...
            'SampleRate',fs, ...
            'PathDelays',[0 1.5]/fs, ...
            'AveragePathGains',[2 3], ...
            'NormalizePathGains',true, ...
            'MaximumDopplerShift',30, ...
            'DopplerSpectrum',{doppler('Gaussian',0.6),doppler('Flat')}, ...
            'RandomStream','mt19937ar with seed', ...
            'Seed',22, ...
            'PathGainsOutputPort',true);
        res=rayChan(x);
    case {"Rician"}
        ricianChan = comm.RicianChannel(...
            'SampleRate',fs,...
            'PathDelays',[0.0 1.8 3.4]/fs,...
            'AveragePathGains',[0 -2 -10],...
            'KFactor',4,...
            'DirectPathDopplerShift',5.0,...
            'DirectPathInitialPhase',0.5,...
            'MaximumDopplerShift',4,...
            'DopplerSpectrum',doppler('Bell', 8),...
            'RandomStream','mt19937ar with seed', ...
            'Seed',73, ...
            'PathGainsOutputPort',true);
        res=ricianChan(x);
    case {"AWGN"}
        res = x;
    otherwise
        error(channel)
end

end